//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Loading_Addresses
    {
        public int Loading_Address_ID { get; set; }
        public Nullable<int> Contact_ID_FK { get; set; }
        public string Loading_Address { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
