//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroup
    {
        public ContactGroup()
        {
            this.Contact_IN_Group = new HashSet<Contact_IN_Group>();
        }
    
        public int ContactGroup_ID { get; set; }
        public string ContactGroup_Name { get; set; }
        public string Notes { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
        public int Created_by { get; set; }
        public int Updated_by { get; set; }
    
        public virtual ICollection<Contact_IN_Group> Contact_IN_Group { get; set; }
    }
}
