//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Contact_IN_Group = new HashSet<Contact_IN_Group>();
            this.Contact_Loading_Addresses = new HashSet<Contact_Loading_Addresses>();
            this.Contact_PICs = new HashSet<Contact_PICs>();
            this.FirstBlanceContacts = new HashSet<FirstBlanceContact>();
        }
    
        public int Contact_ID { get; set; }
        public string Contact_Name { get; set; }
        public byte[] Contact_Logo { get; set; }
        public string Contact_Address { get; set; }
        public string Contact_BL_Address { get; set; }
        public string Contact_Billing_Address { get; set; }
        public string Contact_Phone1 { get; set; }
        public string Contact_Phone2 { get; set; }
        public string Contact_Fax { get; set; }
        public string Contact_EMail { get; set; }
        public string Contact_WebSite { get; set; }
        public Nullable<int> Contact_Credit_Days { get; set; }
        public Nullable<decimal> Contact_Credit_Limit { get; set; }
        public Nullable<int> Contact_Type_ID_FK { get; set; }
        public Nullable<long> Employee_ID_FK { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Last_update { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public string Bank_Details { get; set; }
        public Nullable<int> AccID { get; set; }
        public string Ref_Contract { get; set; }
        public Nullable<int> Prevent_Client_F_Operation { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Commercial_Register { get; set; }
        public string Tax_Certificate { get; set; }
        public bool IsAirline { get; set; }
        public string City { get; set; }
        public string LettersCode { get; set; }
        public string PrefixCode { get; set; }
    
        public virtual ICollection<Contact_IN_Group> Contact_IN_Group { get; set; }
        public virtual ICollection<Contact_Loading_Addresses> Contact_Loading_Addresses { get; set; }
        public virtual ICollection<Contact_PICs> Contact_PICs { get; set; }
        public virtual Contact_Types Contact_Types { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<FirstBlanceContact> FirstBlanceContacts { get; set; }
    }
}
