//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_IN_Group
    {
        public int ContactGroup_ID { get; set; }
        public int Contact_ID_FK { get; set; }
        public int Group_ID_FK { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ContactGroup ContactGroup { get; set; }
    }
}
