//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Country_ID { get; set; }
        public string Country_Name { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
