//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int crrID { get; set; }
        public string crrNAME { get; set; }
        public string crrSymbol { get; set; }
        public Nullable<bool> DfltCrncy { get; set; }
        public Nullable<decimal> ROE { get; set; }
        public string crrNAMEE { get; set; }
        public Nullable<int> FrtCrrId { get; set; }
        public Nullable<int> FltCrrId { get; set; }
        public Nullable<System.DateTime> Fdate { get; set; }
        public Nullable<int> TrmpCrrID { get; set; }
        public Nullable<int> AGNCRRID { get; set; }
    }
}
