//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Contacts = new HashSet<Contact>();
            this.Employees1 = new HashSet<Employee>();
        }
    
        public long Employee_ID { get; set; }
        public Nullable<int> Employee_Code { get; set; }
        public Nullable<int> Branch_Code { get; set; }
        public Nullable<int> Emp_Code { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_NameA { get; set; }
        public string User_ID_FK { get; set; }
        public Nullable<int> TypeOfID_ID_FK { get; set; }
        public string NationalID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender_ID_FK { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> Governorate_ID_FK { get; set; }
        public Nullable<int> AreasLocation_ID_FK { get; set; }
        public string Address { get; set; }
        public string AddressA { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public string OfficePhoneExtension { get; set; }
        public Nullable<int> Branch_ID_FK { get; set; }
        public Nullable<int> Location_ID_FK { get; set; }
        public Nullable<int> OrganizationDetail_ID_FK { get; set; }
        public string SocialInsuranceNO { get; set; }
        public Nullable<System.DateTime> SocialInsuranceDate { get; set; }
        public Nullable<int> InsuranceOffice_ID_FK { get; set; }
        public Nullable<System.DateTime> SocialInsuranceRealEndDate { get; set; }
        public Nullable<System.DateTime> SocialInsuranceEndDate { get; set; }
        public Nullable<int> JobTitle_ID_FK { get; set; }
        public string RFID { get; set; }
        public Nullable<int> ExitReason_ID_FK { get; set; }
        public Nullable<int> MaritalStatus_ID_FK { get; set; }
        public Nullable<int> MilitaryStatus_ID_FK { get; set; }
        public Nullable<int> Nationality_ID_FK { get; set; }
        public Nullable<int> Religion_ID_FK { get; set; }
        public Nullable<System.DateTime> Contract_From { get; set; }
        public Nullable<int> ContractPeriod_ID_FK { get; set; }
        public Nullable<System.DateTime> Contract_To { get; set; }
        public Nullable<decimal> Contract_Amount { get; set; }
        public string Image_Path { get; set; }
        public Nullable<int> Shift_ID_FK { get; set; }
        public Nullable<int> WeekEnd_ID_FK { get; set; }
        public Nullable<bool> ISapproved { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
        public Nullable<long> approved_Request_ID_FK { get; set; }
        public Nullable<int> InsuranceJob_ID_FK { get; set; }
        public Nullable<long> Qualification_ID_FK { get; set; }
        public Nullable<System.DateTime> QualificationDate { get; set; }
        public string Employee_Notes { get; set; }
        public Nullable<long> ReportTO { get; set; }
        public Nullable<bool> Is_resigned { get; set; }
        public Nullable<System.DateTime> LastResignationDate { get; set; }
        public Nullable<bool> ISBalckList { get; set; }
        public Nullable<long> Creation_Employee_ID_FK { get; set; }
        public Nullable<System.DateTime> Creation_date { get; set; }
        public Nullable<long> LastUpdate_Employee_ID_FK { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<int> EnrollNumber { get; set; }
        public Nullable<bool> IsSalaryApproved { get; set; }
        public Nullable<System.DateTime> SalaryapprovedDate { get; set; }
        public Nullable<long> Salaryapproved_Request_ID_FK { get; set; }
        public Nullable<decimal> Pay_BasicSalary { get; set; }
        public Nullable<decimal> Pay_VariableSalary { get; set; }
        public Nullable<bool> Pay_HasAttendance { get; set; }
        public Nullable<bool> Pay_HasOverTime { get; set; }
        public Nullable<bool> Pay_HasTax { get; set; }
        public Nullable<bool> Pay_HasInsurance { get; set; }
        public Nullable<int> Bank_ID_FK { get; set; }
        public Nullable<int> BankBranch_ID_FK { get; set; }
        public string BankAccountNO { get; set; }
        public string BankCodeNO { get; set; }
        public string ERPCode { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ChidrenNO { get; set; }
        public Nullable<int> BirthLocationGovernorate_ID_FK { get; set; }
        public Nullable<System.DateTime> ID_Validto_Date { get; set; }
        public Nullable<System.DateTime> MilitaryStatus_Expiration_Date { get; set; }
        public string HRID { get; set; }
        public Nullable<int> ContractType_ID_FK { get; set; }
        public Nullable<int> EmployeeType_ID_FK { get; set; }
        public Nullable<int> LegalEntity_ID_FK { get; set; }
        public string IDAddress { get; set; }
        public string IDAddressA { get; set; }
        public Nullable<int> Faculty_ID_FK { get; set; }
        public Nullable<int> University_ID_FK { get; set; }
        public string MobilePhoneOther { get; set; }
        public string RegistrationCertificateNo { get; set; }
        public Nullable<System.DateTime> RegistrationCertificateDate { get; set; }
        public bool IsSuperAdmin { get; set; }
        public Nullable<int> JobOffer_ID { get; set; }
        public Nullable<int> RptCostCenter_ID_FK { get; set; }
        public Nullable<int> TaxLowCategoryID_FK { get; set; }
        public string Employee_Ref { get; set; }
        public string Employee_Serial { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<bool> See_Selling { get; set; }
        public Nullable<bool> See_Buying { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public bool Is_Operation { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
