//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPWeb_WorldTransEntities : DbContext
    {
        public ERPWeb_WorldTransEntities()
            : base("name=ERPWeb_WorldTransEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Contact_IN_Group> Contact_IN_Group { get; set; }
        public virtual DbSet<Contact_Loading_Addresses> Contact_Loading_Addresses { get; set; }
        public virtual DbSet<Contact_PICs> Contact_PICs { get; set; }
        public virtual DbSet<Contact_Types> Contact_Types { get; set; }
        public virtual DbSet<ContactGroup> ContactGroups { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<FirstBlanceContact> FirstBlanceContacts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Acct> Accts { get; set; }
    }
}
