//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPApplicationWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstBlanceContact
    {
        public int Contact_Balance_ID { get; set; }
        public Nullable<decimal> Contact_Balance_Name { get; set; }
        public Nullable<int> Contact_Balance_Currency { get; set; }
        public Nullable<int> Fk_Contact_ID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
